/** Edge Read Aloud 音色表（由 scripts/generate-edge-tts-voices.mjs 生成） */

export type EdgeTtsVoiceGender = "male" | "female";

export type EdgeTtsVoice = {
  id: string;
  lang: string;
  gender: EdgeTtsVoiceGender;
  /** 英文短名，如 Xiaoxiao */
  name: string;
  /** 官方/通用中文名（仅中文及相关方言音色） */
  nameZh?: string;
  /** 下拉主行文案 */
  label: string;
  /** 下拉副行说明 */
  description?: string;
};

function edgeVoice(
  id: string,
  lang: string,
  gender: EdgeTtsVoiceGender,
  name: string,
  label: string,
  nameZh?: string,
  description?: string,
): EdgeTtsVoice {
  return { id, lang, gender, name, nameZh, label, description };
}

/** 与 Edge Read Aloud 在线列表同步的 Neural 音色 */
export const EDGE_TTS_VOICES: readonly EdgeTtsVoice[] = [
  // edgeVoice("af-ZA-AdriNeural", "af-ZA", "female", "Adri", "Adri", undefined, "Friendly, Positive · General"),
  // edgeVoice("af-ZA-WillemNeural", "af-ZA", "male", "Willem", "Willem", undefined, "Friendly, Positive · General"),
  // edgeVoice("am-ET-AmehaNeural", "am-ET", "male", "Ameha", "Ameha", undefined, "Friendly, Positive · General"),
  // edgeVoice("am-ET-MekdesNeural", "am-ET", "female", "Mekdes", "Mekdes", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-AE-FatimaNeural", "ar-AE", "female", "Fatima", "Fatima", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-AE-HamdanNeural", "ar-AE", "male", "Hamdan", "Hamdan", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-BH-AliNeural", "ar-BH", "male", "Ali", "Ali", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-BH-LailaNeural", "ar-BH", "female", "Laila", "Laila", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-DZ-AminaNeural", "ar-DZ", "female", "Amina", "Amina", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-DZ-IsmaelNeural", "ar-DZ", "male", "Ismael", "Ismael", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-EG-SalmaNeural", "ar-EG", "female", "Salma", "Salma", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-EG-ShakirNeural", "ar-EG", "male", "Shakir", "Shakir", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-IQ-BasselNeural", "ar-IQ", "male", "Bassel", "Bassel", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-IQ-RanaNeural", "ar-IQ", "female", "Rana", "Rana", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-JO-SanaNeural", "ar-JO", "female", "Sana", "Sana", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-JO-TaimNeural", "ar-JO", "male", "Taim", "Taim", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-KW-FahedNeural", "ar-KW", "male", "Fahed", "Fahed", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-KW-NouraNeural", "ar-KW", "female", "Noura", "Noura", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-LB-LaylaNeural", "ar-LB", "female", "Layla", "Layla", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-LB-RamiNeural", "ar-LB", "male", "Rami", "Rami", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-LY-ImanNeural", "ar-LY", "female", "Iman", "Iman", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-LY-OmarNeural", "ar-LY", "male", "Omar", "Omar", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-MA-JamalNeural", "ar-MA", "male", "Jamal", "Jamal", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-MA-MounaNeural", "ar-MA", "female", "Mouna", "Mouna", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-OM-AbdullahNeural", "ar-OM", "male", "Abdullah", "Abdullah", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-OM-AyshaNeural", "ar-OM", "female", "Aysha", "Aysha", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-QA-AmalNeural", "ar-QA", "female", "Amal", "Amal", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-QA-MoazNeural", "ar-QA", "male", "Moaz", "Moaz", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-SA-HamedNeural", "ar-SA", "male", "Hamed", "Hamed", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-SA-ZariyahNeural", "ar-SA", "female", "Zariyah", "Zariyah", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-SY-AmanyNeural", "ar-SY", "female", "Amany", "Amany", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-SY-LaithNeural", "ar-SY", "male", "Laith", "Laith", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-TN-HediNeural", "ar-TN", "male", "Hedi", "Hedi", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-TN-ReemNeural", "ar-TN", "female", "Reem", "Reem", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-YE-MaryamNeural", "ar-YE", "female", "Maryam", "Maryam", undefined, "Friendly, Positive · General"),
  // edgeVoice("ar-YE-SalehNeural", "ar-YE", "male", "Saleh", "Saleh", undefined, "Friendly, Positive · General"),
  // edgeVoice("az-AZ-BabekNeural", "az-AZ", "male", "Babek", "Babek", undefined, "Friendly, Positive · General"),
  // edgeVoice("az-AZ-BanuNeural", "az-AZ", "female", "Banu", "Banu", undefined, "Friendly, Positive · General"),
  // edgeVoice("bg-BG-BorislavNeural", "bg-BG", "male", "Borislav", "Borislav", undefined, "Friendly, Positive · General"),
  // edgeVoice("bg-BG-KalinaNeural", "bg-BG", "female", "Kalina", "Kalina", undefined, "Friendly, Positive · General"),
  // edgeVoice("bn-BD-NabanitaNeural", "bn-BD", "female", "Nabanita", "Nabanita", undefined, "Friendly, Positive · General"),
  // edgeVoice("bn-BD-PradeepNeural", "bn-BD", "male", "Pradeep", "Pradeep", undefined, "Friendly, Positive · General"),
  // edgeVoice("bn-IN-BashkarNeural", "bn-IN", "male", "Bashkar", "Bashkar", undefined, "Friendly, Positive · General"),
  // edgeVoice("bn-IN-TanishaaNeural", "bn-IN", "female", "Tanishaa", "Tanishaa", undefined, "Friendly, Positive · General"),
  // edgeVoice("bs-BA-GoranNeural", "bs-BA", "male", "Goran", "Goran", undefined, "Friendly, Positive · General"),
  // edgeVoice("bs-BA-VesnaNeural", "bs-BA", "female", "Vesna", "Vesna", undefined, "Friendly, Positive · General"),
  // edgeVoice("ca-ES-EnricNeural", "ca-ES", "male", "Enric", "Enric", undefined, "Friendly, Positive · General"),
  // edgeVoice("ca-ES-JoanaNeural", "ca-ES", "female", "Joana", "Joana", undefined, "Friendly, Positive · General"),
  // edgeVoice("cs-CZ-AntoninNeural", "cs-CZ", "male", "Antonin", "Antonin", undefined, "Friendly, Positive · General"),
  // edgeVoice("cs-CZ-VlastaNeural", "cs-CZ", "female", "Vlasta", "Vlasta", undefined, "Friendly, Positive · General"),
  // edgeVoice("cy-GB-AledNeural", "cy-GB", "male", "Aled", "Aled", undefined, "Friendly, Positive · General"),
  // edgeVoice("cy-GB-NiaNeural", "cy-GB", "female", "Nia", "Nia", undefined, "Friendly, Positive · General"),
  // edgeVoice("da-DK-ChristelNeural", "da-DK", "female", "Christel", "Christel", undefined, "Friendly, Positive · General"),
  // edgeVoice("da-DK-JeppeNeural", "da-DK", "male", "Jeppe", "Jeppe", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-AT-IngridNeural", "de-AT", "female", "Ingrid", "Ingrid", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-AT-JonasNeural", "de-AT", "male", "Jonas", "Jonas", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-CH-JanNeural", "de-CH", "male", "Jan", "Jan", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-CH-LeniNeural", "de-CH", "female", "Leni", "Leni", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-AmalaNeural", "de-DE", "female", "Amala", "Amala", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-ConradNeural", "de-DE", "male", "Conrad", "Conrad", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-FlorianMultilingualNeural", "de-DE", "male", "FlorianMultilingual", "FlorianMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-KatjaNeural", "de-DE", "female", "Katja", "Katja", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-KillianNeural", "de-DE", "male", "Killian", "Killian", undefined, "Friendly, Positive · General"),
  // edgeVoice("de-DE-SeraphinaMultilingualNeural", "de-DE", "female", "SeraphinaMultilingual", "SeraphinaMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("el-GR-AthinaNeural", "el-GR", "female", "Athina", "Athina", undefined, "Friendly, Positive · General"),
  // edgeVoice("el-GR-NestorasNeural", "el-GR", "male", "Nestoras", "Nestoras", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-AU-NatashaNeural", "en-AU", "female", "Natasha", "Natasha", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-AU-WilliamMultilingualNeural", "en-AU", "male", "WilliamMultilingual", "WilliamMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-CA-ClaraNeural", "en-CA", "female", "Clara", "Clara", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-CA-LiamNeural", "en-CA", "male", "Liam", "Liam", undefined, "Friendly, Positive · General"),
  edgeVoice("en-GB-LibbyNeural", "en-GB", "female", "Libby", "Libby", undefined, "Friendly, Positive · General"),
  edgeVoice("en-GB-MaisieNeural", "en-GB", "female", "Maisie", "Maisie", undefined, "Friendly, Positive · General"),
  edgeVoice("en-GB-RyanNeural", "en-GB", "male", "Ryan", "Ryan", undefined, "Friendly, Positive · General"),
  edgeVoice("en-GB-SoniaNeural", "en-GB", "female", "Sonia", "Sonia", undefined, "Friendly, Positive · General"),
  edgeVoice("en-GB-ThomasNeural", "en-GB", "male", "Thomas", "Thomas", undefined, "Friendly, Positive · General"),
  edgeVoice("en-HK-SamNeural", "en-HK", "male", "Sam", "Sam", undefined, "Friendly, Positive · General"),
  edgeVoice("en-HK-YanNeural", "en-HK", "female", "Yan", "Yan", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-IE-ConnorNeural", "en-IE", "male", "Connor", "Connor", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-IE-EmilyNeural", "en-IE", "female", "Emily", "Emily", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-IN-NeerjaExpressiveNeural", "en-IN", "female", "NeerjaExpressive", "NeerjaExpressive", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-IN-NeerjaNeural", "en-IN", "female", "Neerja", "Neerja", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-IN-PrabhatNeural", "en-IN", "male", "Prabhat", "Prabhat", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-KE-AsiliaNeural", "en-KE", "female", "Asilia", "Asilia", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-KE-ChilembaNeural", "en-KE", "male", "Chilemba", "Chilemba", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-NG-AbeoNeural", "en-NG", "male", "Abeo", "Abeo", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-NG-EzinneNeural", "en-NG", "female", "Ezinne", "Ezinne", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-NZ-MitchellNeural", "en-NZ", "male", "Mitchell", "Mitchell", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-NZ-MollyNeural", "en-NZ", "female", "Molly", "Molly", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-PH-JamesNeural", "en-PH", "male", "James", "James", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-PH-RosaNeural", "en-PH", "female", "Rosa", "Rosa", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-SG-LunaNeural", "en-SG", "female", "Luna", "Luna", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-SG-WayneNeural", "en-SG", "male", "Wayne", "Wayne", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-TZ-ElimuNeural", "en-TZ", "male", "Elimu", "Elimu", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-TZ-ImaniNeural", "en-TZ", "female", "Imani", "Imani", undefined, "Friendly, Positive · General"),
  edgeVoice("en-US-AnaNeural", "en-US", "female", "Ana", "Ana", undefined, "Cute · Cartoon, Conversation"),
  edgeVoice("en-US-AndrewMultilingualNeural", "en-US", "male", "AndrewMultilingual", "AndrewMultilingual", undefined, "Warm, Confident, Authentic, Honest · Conversation, Copilot"),
  edgeVoice("en-US-AndrewNeural", "en-US", "male", "Andrew", "Andrew", undefined, "Warm, Confident, Authentic, Honest · Conversation, Copilot"),
  edgeVoice("en-US-AriaNeural", "en-US", "female", "Aria", "Aria", undefined, "Positive, Confident · News, Novel"),
  edgeVoice("en-US-AvaMultilingualNeural", "en-US", "female", "AvaMultilingual", "AvaMultilingual", undefined, "Expressive, Caring, Pleasant, Friendly · Conversation, Copilot"),
  edgeVoice("en-US-AvaNeural", "en-US", "female", "Ava", "Ava", undefined, "Expressive, Caring, Pleasant, Friendly · Conversation, Copilot"),
  edgeVoice("en-US-BrianMultilingualNeural", "en-US", "male", "BrianMultilingual", "BrianMultilingual", undefined, "Approachable, Casual, Sincere · Conversation, Copilot"),
  edgeVoice("en-US-BrianNeural", "en-US", "male", "Brian", "Brian", undefined, "Approachable, Casual, Sincere · Conversation, Copilot"),
  edgeVoice("en-US-ChristopherNeural", "en-US", "male", "Christopher", "Christopher", undefined, "Reliable, Authority · News, Novel"),
  edgeVoice("en-US-EmmaMultilingualNeural", "en-US", "female", "EmmaMultilingual", "EmmaMultilingual", undefined, "Cheerful, Clear, Conversational · Conversation, Copilot"),
  edgeVoice("en-US-EmmaNeural", "en-US", "female", "Emma", "Emma", undefined, "Cheerful, Clear, Conversational · Conversation, Copilot"),
  edgeVoice("en-US-EricNeural", "en-US", "male", "Eric", "Eric", undefined, "Rational · News, Novel"),
  edgeVoice("en-US-GuyNeural", "en-US", "male", "Guy", "Guy", undefined, "Passion · News, Novel"),
  edgeVoice("en-US-JennyNeural", "en-US", "female", "Jenny", "Jenny", undefined, "Friendly, Considerate, Comfort · General"),
  edgeVoice("en-US-MichelleNeural", "en-US", "female", "Michelle", "Michelle", undefined, "Friendly, Pleasant · News, Novel"),
  edgeVoice("en-US-RogerNeural", "en-US", "male", "Roger", "Roger", undefined, "Lively · News, Novel"),
  edgeVoice("en-US-SteffanNeural", "en-US", "male", "Steffan", "Steffan", undefined, "Rational · News, Novel"),
  // edgeVoice("en-ZA-LeahNeural", "en-ZA", "female", "Leah", "Leah", undefined, "Friendly, Positive · General"),
  // edgeVoice("en-ZA-LukeNeural", "en-ZA", "male", "Luke", "Luke", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-AR-ElenaNeural", "es-AR", "female", "Elena", "Elena", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-AR-TomasNeural", "es-AR", "male", "Tomas", "Tomas", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-BO-MarceloNeural", "es-BO", "male", "Marcelo", "Marcelo", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-BO-SofiaNeural", "es-BO", "female", "Sofia", "Sofia", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CL-CatalinaNeural", "es-CL", "female", "Catalina", "Catalina", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CL-LorenzoNeural", "es-CL", "male", "Lorenzo", "Lorenzo", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CO-GonzaloNeural", "es-CO", "male", "Gonzalo", "Gonzalo", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CO-SalomeNeural", "es-CO", "female", "Salome", "Salome", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CR-JuanNeural", "es-CR", "male", "Juan", "Juan", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CR-MariaNeural", "es-CR", "female", "Maria", "Maria", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CU-BelkysNeural", "es-CU", "female", "Belkys", "Belkys", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-CU-ManuelNeural", "es-CU", "male", "Manuel", "Manuel", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-DO-EmilioNeural", "es-DO", "male", "Emilio", "Emilio", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-DO-RamonaNeural", "es-DO", "female", "Ramona", "Ramona", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-EC-AndreaNeural", "es-EC", "female", "Andrea", "Andrea", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-EC-LuisNeural", "es-EC", "male", "Luis", "Luis", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-ES-AlvaroNeural", "es-ES", "male", "Alvaro", "Alvaro", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-ES-ElviraNeural", "es-ES", "female", "Elvira", "Elvira", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-ES-XimenaNeural", "es-ES", "female", "Ximena", "Ximena", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-GQ-JavierNeural", "es-GQ", "male", "Javier", "Javier", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-GQ-TeresaNeural", "es-GQ", "female", "Teresa", "Teresa", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-GT-AndresNeural", "es-GT", "male", "Andres", "Andres", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-GT-MartaNeural", "es-GT", "female", "Marta", "Marta", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-HN-CarlosNeural", "es-HN", "male", "Carlos", "Carlos", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-HN-KarlaNeural", "es-HN", "female", "Karla", "Karla", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-MX-DaliaNeural", "es-MX", "female", "Dalia", "Dalia", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-MX-JorgeNeural", "es-MX", "male", "Jorge", "Jorge", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-NI-FedericoNeural", "es-NI", "male", "Federico", "Federico", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-NI-YolandaNeural", "es-NI", "female", "Yolanda", "Yolanda", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PA-MargaritaNeural", "es-PA", "female", "Margarita", "Margarita", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PA-RobertoNeural", "es-PA", "male", "Roberto", "Roberto", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PE-AlexNeural", "es-PE", "male", "Alex", "Alex", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PE-CamilaNeural", "es-PE", "female", "Camila", "Camila", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PR-KarinaNeural", "es-PR", "female", "Karina", "Karina", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PR-VictorNeural", "es-PR", "male", "Victor", "Victor", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PY-MarioNeural", "es-PY", "male", "Mario", "Mario", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-PY-TaniaNeural", "es-PY", "female", "Tania", "Tania", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-SV-LorenaNeural", "es-SV", "female", "Lorena", "Lorena", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-SV-RodrigoNeural", "es-SV", "male", "Rodrigo", "Rodrigo", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-US-AlonsoNeural", "es-US", "male", "Alonso", "Alonso", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-US-PalomaNeural", "es-US", "female", "Paloma", "Paloma", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-UY-MateoNeural", "es-UY", "male", "Mateo", "Mateo", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-UY-ValentinaNeural", "es-UY", "female", "Valentina", "Valentina", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-VE-PaolaNeural", "es-VE", "female", "Paola", "Paola", undefined, "Friendly, Positive · General"),
  // edgeVoice("es-VE-SebastianNeural", "es-VE", "male", "Sebastian", "Sebastian", undefined, "Friendly, Positive · General"),
  // edgeVoice("et-EE-AnuNeural", "et-EE", "female", "Anu", "Anu", undefined, "Friendly, Positive · General"),
  // edgeVoice("et-EE-KertNeural", "et-EE", "male", "Kert", "Kert", undefined, "Friendly, Positive · General"),
  // edgeVoice("fa-IR-DilaraNeural", "fa-IR", "female", "Dilara", "Dilara", undefined, "Friendly, Positive · General"),
  // edgeVoice("fa-IR-FaridNeural", "fa-IR", "male", "Farid", "Farid", undefined, "Friendly, Positive · General"),
  // edgeVoice("fi-FI-HarriNeural", "fi-FI", "male", "Harri", "Harri", undefined, "Friendly, Positive · General"),
  // edgeVoice("fi-FI-NooraNeural", "fi-FI", "female", "Noora", "Noora", undefined, "Friendly, Positive · General"),
  // edgeVoice("fil-PH-AngeloNeural", "fil-PH", "male", "Angelo", "Angelo", undefined, "Friendly, Positive · General"),
  // edgeVoice("fil-PH-BlessicaNeural", "fil-PH", "female", "Blessica", "Blessica", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-BE-CharlineNeural", "fr-BE", "female", "Charline", "Charline", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-BE-GerardNeural", "fr-BE", "male", "Gerard", "Gerard", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CA-AntoineNeural", "fr-CA", "male", "Antoine", "Antoine", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CA-JeanNeural", "fr-CA", "male", "Jean", "Jean", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CA-SylvieNeural", "fr-CA", "female", "Sylvie", "Sylvie", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CA-ThierryNeural", "fr-CA", "male", "Thierry", "Thierry", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CH-ArianeNeural", "fr-CH", "female", "Ariane", "Ariane", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-CH-FabriceNeural", "fr-CH", "male", "Fabrice", "Fabrice", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-FR-DeniseNeural", "fr-FR", "female", "Denise", "Denise", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-FR-EloiseNeural", "fr-FR", "female", "Eloise", "Eloise", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-FR-HenriNeural", "fr-FR", "male", "Henri", "Henri", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-FR-RemyMultilingualNeural", "fr-FR", "male", "RemyMultilingual", "RemyMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("fr-FR-VivienneMultilingualNeural", "fr-FR", "female", "VivienneMultilingual", "VivienneMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("ga-IE-ColmNeural", "ga-IE", "male", "Colm", "Colm", undefined, "Friendly, Positive · General"),
  // edgeVoice("ga-IE-OrlaNeural", "ga-IE", "female", "Orla", "Orla", undefined, "Friendly, Positive · General"),
  // edgeVoice("gl-ES-RoiNeural", "gl-ES", "male", "Roi", "Roi", undefined, "Friendly, Positive · General"),
  // edgeVoice("gl-ES-SabelaNeural", "gl-ES", "female", "Sabela", "Sabela", undefined, "Friendly, Positive · General"),
  // edgeVoice("gu-IN-DhwaniNeural", "gu-IN", "female", "Dhwani", "Dhwani", undefined, "Friendly, Positive · General"),
  // edgeVoice("gu-IN-NiranjanNeural", "gu-IN", "male", "Niranjan", "Niranjan", undefined, "Friendly, Positive · General"),
  // edgeVoice("he-IL-AvriNeural", "he-IL", "male", "Avri", "Avri", undefined, "Friendly, Positive · General"),
  // edgeVoice("he-IL-HilaNeural", "he-IL", "female", "Hila", "Hila", undefined, "Friendly, Positive · General"),
  // edgeVoice("hi-IN-MadhurNeural", "hi-IN", "male", "Madhur", "Madhur", undefined, "Friendly, Positive · General"),
  // edgeVoice("hi-IN-SwaraNeural", "hi-IN", "female", "Swara", "Swara", undefined, "Friendly, Positive · General"),
  // edgeVoice("hr-HR-GabrijelaNeural", "hr-HR", "female", "Gabrijela", "Gabrijela", undefined, "Friendly, Positive · General"),
  // edgeVoice("hr-HR-SreckoNeural", "hr-HR", "male", "Srecko", "Srecko", undefined, "Friendly, Positive · General"),
  // edgeVoice("hu-HU-NoemiNeural", "hu-HU", "female", "Noemi", "Noemi", undefined, "Friendly, Positive · General"),
  // edgeVoice("hu-HU-TamasNeural", "hu-HU", "male", "Tamas", "Tamas", undefined, "Friendly, Positive · General"),
  // edgeVoice("id-ID-ArdiNeural", "id-ID", "male", "Ardi", "Ardi", undefined, "Friendly, Positive · General"),
  // edgeVoice("id-ID-GadisNeural", "id-ID", "female", "Gadis", "Gadis", undefined, "Friendly, Positive · General"),
  // edgeVoice("is-IS-GudrunNeural", "is-IS", "female", "Gudrun", "Gudrun", undefined, "Friendly, Positive · General"),
  // edgeVoice("is-IS-GunnarNeural", "is-IS", "male", "Gunnar", "Gunnar", undefined, "Friendly, Positive · General"),
  // edgeVoice("it-IT-DiegoNeural", "it-IT", "male", "Diego", "Diego", undefined, "Friendly, Positive · General"),
  // edgeVoice("it-IT-ElsaNeural", "it-IT", "female", "Elsa", "Elsa", undefined, "Friendly, Positive · General"),
  // edgeVoice("it-IT-GiuseppeMultilingualNeural", "it-IT", "male", "GiuseppeMultilingual", "GiuseppeMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("it-IT-IsabellaNeural", "it-IT", "female", "Isabella", "Isabella", undefined, "Friendly, Positive · General"),
  // edgeVoice("iu-Cans-CA-SiqiniqNeural", "iu-Cans-CA", "female", "Siqiniq", "Siqiniq", undefined, "Friendly, Positive · General"),
  // edgeVoice("iu-Cans-CA-TaqqiqNeural", "iu-Cans-CA", "male", "Taqqiq", "Taqqiq", undefined, "Friendly, Positive · General"),
  // edgeVoice("iu-Latn-CA-SiqiniqNeural", "iu-Latn-CA", "female", "Siqiniq", "Siqiniq", undefined, "Friendly, Positive · General"),
  // edgeVoice("iu-Latn-CA-TaqqiqNeural", "iu-Latn-CA", "male", "Taqqiq", "Taqqiq", undefined, "Friendly, Positive · General"),
  edgeVoice("ja-JP-KeitaNeural", "ja-JP", "male", "Keita", "Keita", undefined, "Friendly, Positive · General"),
  edgeVoice("ja-JP-NanamiNeural", "ja-JP", "female", "Nanami", "Nanami", undefined, "Friendly, Positive · General"),
  // edgeVoice("jv-ID-DimasNeural", "jv-ID", "male", "Dimas", "Dimas", undefined, "Friendly, Positive · General"),
  // edgeVoice("jv-ID-SitiNeural", "jv-ID", "female", "Siti", "Siti", undefined, "Friendly, Positive · General"),
  // edgeVoice("ka-GE-EkaNeural", "ka-GE", "female", "Eka", "Eka", undefined, "Friendly, Positive · General"),
  // edgeVoice("ka-GE-GiorgiNeural", "ka-GE", "male", "Giorgi", "Giorgi", undefined, "Friendly, Positive · General"),
  // edgeVoice("kk-KZ-AigulNeural", "kk-KZ", "female", "Aigul", "Aigul", undefined, "Friendly, Positive · General"),
  // edgeVoice("kk-KZ-DauletNeural", "kk-KZ", "male", "Daulet", "Daulet", undefined, "Friendly, Positive · General"),
  // edgeVoice("km-KH-PisethNeural", "km-KH", "male", "Piseth", "Piseth", undefined, "Friendly, Positive · General"),
  // edgeVoice("km-KH-SreymomNeural", "km-KH", "female", "Sreymom", "Sreymom", undefined, "Friendly, Positive · General"),
  // edgeVoice("kn-IN-GaganNeural", "kn-IN", "male", "Gagan", "Gagan", undefined, "Friendly, Positive · General"),
  // edgeVoice("kn-IN-SapnaNeural", "kn-IN", "female", "Sapna", "Sapna", undefined, "Friendly, Positive · General"),
  edgeVoice("ko-KR-HyunsuMultilingualNeural", "ko-KR", "male", "HyunsuMultilingual", "HyunsuMultilingual", undefined, "Friendly, Positive · General"),
  edgeVoice("ko-KR-InJoonNeural", "ko-KR", "male", "InJoon", "InJoon", undefined, "Friendly, Positive · General"),
  edgeVoice("ko-KR-SunHiNeural", "ko-KR", "female", "SunHi", "SunHi", undefined, "Friendly, Positive · General"),
  // edgeVoice("lo-LA-ChanthavongNeural", "lo-LA", "male", "Chanthavong", "Chanthavong", undefined, "Friendly, Positive · General"),
  // edgeVoice("lo-LA-KeomanyNeural", "lo-LA", "female", "Keomany", "Keomany", undefined, "Friendly, Positive · General"),
  // edgeVoice("lt-LT-LeonasNeural", "lt-LT", "male", "Leonas", "Leonas", undefined, "Friendly, Positive · General"),
  // edgeVoice("lt-LT-OnaNeural", "lt-LT", "female", "Ona", "Ona", undefined, "Friendly, Positive · General"),
  // edgeVoice("lv-LV-EveritaNeural", "lv-LV", "female", "Everita", "Everita", undefined, "Friendly, Positive · General"),
  // edgeVoice("lv-LV-NilsNeural", "lv-LV", "male", "Nils", "Nils", undefined, "Friendly, Positive · General"),
  // edgeVoice("mk-MK-AleksandarNeural", "mk-MK", "male", "Aleksandar", "Aleksandar", undefined, "Friendly, Positive · General"),
  // edgeVoice("mk-MK-MarijaNeural", "mk-MK", "female", "Marija", "Marija", undefined, "Friendly, Positive · General"),
  // edgeVoice("ml-IN-MidhunNeural", "ml-IN", "male", "Midhun", "Midhun", undefined, "Friendly, Positive · General"),
  // edgeVoice("ml-IN-SobhanaNeural", "ml-IN", "female", "Sobhana", "Sobhana", undefined, "Friendly, Positive · General"),
  // edgeVoice("mn-MN-BataaNeural", "mn-MN", "male", "Bataa", "Bataa", undefined, "Friendly, Positive · General"),
  // edgeVoice("mn-MN-YesuiNeural", "mn-MN", "female", "Yesui", "Yesui", undefined, "Friendly, Positive · General"),
  // edgeVoice("mr-IN-AarohiNeural", "mr-IN", "female", "Aarohi", "Aarohi", undefined, "Friendly, Positive · General"),
  // edgeVoice("mr-IN-ManoharNeural", "mr-IN", "male", "Manohar", "Manohar", undefined, "Friendly, Positive · General"),
  // edgeVoice("ms-MY-OsmanNeural", "ms-MY", "male", "Osman", "Osman", undefined, "Friendly, Positive · General"),
  // edgeVoice("ms-MY-YasminNeural", "ms-MY", "female", "Yasmin", "Yasmin", undefined, "Friendly, Positive · General"),
  // edgeVoice("mt-MT-GraceNeural", "mt-MT", "female", "Grace", "Grace", undefined, "Friendly, Positive · General"),
  // edgeVoice("mt-MT-JosephNeural", "mt-MT", "male", "Joseph", "Joseph", undefined, "Friendly, Positive · General"),
  // edgeVoice("my-MM-NilarNeural", "my-MM", "female", "Nilar", "Nilar", undefined, "Friendly, Positive · General"),
  // edgeVoice("my-MM-ThihaNeural", "my-MM", "male", "Thiha", "Thiha", undefined, "Friendly, Positive · General"),
  // edgeVoice("nb-NO-FinnNeural", "nb-NO", "male", "Finn", "Finn", undefined, "Friendly, Positive · General"),
  // edgeVoice("nb-NO-PernilleNeural", "nb-NO", "female", "Pernille", "Pernille", undefined, "Friendly, Positive · General"),
  // edgeVoice("ne-NP-HemkalaNeural", "ne-NP", "female", "Hemkala", "Hemkala", undefined, "Friendly, Positive · General"),
  // edgeVoice("ne-NP-SagarNeural", "ne-NP", "male", "Sagar", "Sagar", undefined, "Friendly, Positive · General"),
  // edgeVoice("nl-BE-ArnaudNeural", "nl-BE", "male", "Arnaud", "Arnaud", undefined, "Friendly, Positive · General"),
  // edgeVoice("nl-BE-DenaNeural", "nl-BE", "female", "Dena", "Dena", undefined, "Friendly, Positive · General"),
  // edgeVoice("nl-NL-ColetteNeural", "nl-NL", "female", "Colette", "Colette", undefined, "Friendly, Positive · General"),
  // edgeVoice("nl-NL-FennaNeural", "nl-NL", "female", "Fenna", "Fenna", undefined, "Friendly, Positive · General"),
  // edgeVoice("nl-NL-MaartenNeural", "nl-NL", "male", "Maarten", "Maarten", undefined, "Friendly, Positive · General"),
  // edgeVoice("pl-PL-MarekNeural", "pl-PL", "male", "Marek", "Marek", undefined, "Friendly, Positive · General"),
  // edgeVoice("pl-PL-ZofiaNeural", "pl-PL", "female", "Zofia", "Zofia", undefined, "Friendly, Positive · General"),
  // edgeVoice("ps-AF-GulNawazNeural", "ps-AF", "male", "GulNawaz", "GulNawaz", undefined, "Friendly, Positive · General"),
  // edgeVoice("ps-AF-LatifaNeural", "ps-AF", "female", "Latifa", "Latifa", undefined, "Friendly, Positive · General"),
  // edgeVoice("pt-BR-AntonioNeural", "pt-BR", "male", "Antonio", "Antonio", undefined, "Friendly, Positive · General"),
  // edgeVoice("pt-BR-FranciscaNeural", "pt-BR", "female", "Francisca", "Francisca", undefined, "Friendly, Positive · General"),
  // edgeVoice("pt-BR-ThalitaMultilingualNeural", "pt-BR", "female", "ThalitaMultilingual", "ThalitaMultilingual", undefined, "Friendly, Positive · General"),
  // edgeVoice("pt-PT-DuarteNeural", "pt-PT", "male", "Duarte", "Duarte", undefined, "Friendly, Positive · General"),
  // edgeVoice("pt-PT-RaquelNeural", "pt-PT", "female", "Raquel", "Raquel", undefined, "Friendly, Positive · General"),
  // edgeVoice("ro-RO-AlinaNeural", "ro-RO", "female", "Alina", "Alina", undefined, "Friendly, Positive · General"),
  // edgeVoice("ro-RO-EmilNeural", "ro-RO", "male", "Emil", "Emil", undefined, "Friendly, Positive · General"),
  // edgeVoice("ru-RU-DmitryNeural", "ru-RU", "male", "Dmitry", "Dmitry", undefined, "Friendly, Positive · General"),
  // edgeVoice("ru-RU-SvetlanaNeural", "ru-RU", "female", "Svetlana", "Svetlana", undefined, "Friendly, Positive · General"),
  // edgeVoice("si-LK-SameeraNeural", "si-LK", "male", "Sameera", "Sameera", undefined, "Friendly, Positive · General"),
  // edgeVoice("si-LK-ThiliniNeural", "si-LK", "female", "Thilini", "Thilini", undefined, "Friendly, Positive · General"),
  // edgeVoice("sk-SK-LukasNeural", "sk-SK", "male", "Lukas", "Lukas", undefined, "Friendly, Positive · General"),
  // edgeVoice("sk-SK-ViktoriaNeural", "sk-SK", "female", "Viktoria", "Viktoria", undefined, "Friendly, Positive · General"),
  // edgeVoice("sl-SI-PetraNeural", "sl-SI", "female", "Petra", "Petra", undefined, "Friendly, Positive · General"),
  // edgeVoice("sl-SI-RokNeural", "sl-SI", "male", "Rok", "Rok", undefined, "Friendly, Positive · General"),
  // edgeVoice("so-SO-MuuseNeural", "so-SO", "male", "Muuse", "Muuse", undefined, "Friendly, Positive · General"),
  // edgeVoice("so-SO-UbaxNeural", "so-SO", "female", "Ubax", "Ubax", undefined, "Friendly, Positive · General"),
  // edgeVoice("sq-AL-AnilaNeural", "sq-AL", "female", "Anila", "Anila", undefined, "Friendly, Positive · General"),
  // edgeVoice("sq-AL-IlirNeural", "sq-AL", "male", "Ilir", "Ilir", undefined, "Friendly, Positive · General"),
  // edgeVoice("sr-RS-NicholasNeural", "sr-RS", "male", "Nicholas", "Nicholas", undefined, "Friendly, Positive · General"),
  // edgeVoice("sr-RS-SophieNeural", "sr-RS", "female", "Sophie", "Sophie", undefined, "Friendly, Positive · General"),
  // edgeVoice("su-ID-JajangNeural", "su-ID", "male", "Jajang", "Jajang", undefined, "Friendly, Positive · General"),
  // edgeVoice("su-ID-TutiNeural", "su-ID", "female", "Tuti", "Tuti", undefined, "Friendly, Positive · General"),
  // edgeVoice("sv-SE-MattiasNeural", "sv-SE", "male", "Mattias", "Mattias", undefined, "Friendly, Positive · General"),
  // edgeVoice("sv-SE-SofieNeural", "sv-SE", "female", "Sofie", "Sofie", undefined, "Friendly, Positive · General"),
  // edgeVoice("sw-KE-RafikiNeural", "sw-KE", "male", "Rafiki", "Rafiki", undefined, "Friendly, Positive · General"),
  // edgeVoice("sw-KE-ZuriNeural", "sw-KE", "female", "Zuri", "Zuri", undefined, "Friendly, Positive · General"),
  // edgeVoice("sw-TZ-DaudiNeural", "sw-TZ", "male", "Daudi", "Daudi", undefined, "Friendly, Positive · General"),
  // edgeVoice("sw-TZ-RehemaNeural", "sw-TZ", "female", "Rehema", "Rehema", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-IN-PallaviNeural", "ta-IN", "female", "Pallavi", "Pallavi", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-IN-ValluvarNeural", "ta-IN", "male", "Valluvar", "Valluvar", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-LK-KumarNeural", "ta-LK", "male", "Kumar", "Kumar", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-LK-SaranyaNeural", "ta-LK", "female", "Saranya", "Saranya", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-MY-KaniNeural", "ta-MY", "female", "Kani", "Kani", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-MY-SuryaNeural", "ta-MY", "male", "Surya", "Surya", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-SG-AnbuNeural", "ta-SG", "male", "Anbu", "Anbu", undefined, "Friendly, Positive · General"),
  // edgeVoice("ta-SG-VenbaNeural", "ta-SG", "female", "Venba", "Venba", undefined, "Friendly, Positive · General"),
  // edgeVoice("te-IN-MohanNeural", "te-IN", "male", "Mohan", "Mohan", undefined, "Friendly, Positive · General"),
  // edgeVoice("te-IN-ShrutiNeural", "te-IN", "female", "Shruti", "Shruti", undefined, "Friendly, Positive · General"),
  // edgeVoice("th-TH-NiwatNeural", "th-TH", "male", "Niwat", "Niwat", undefined, "Friendly, Positive · General"),
  // edgeVoice("th-TH-PremwadeeNeural", "th-TH", "female", "Premwadee", "Premwadee", undefined, "Friendly, Positive · General"),
  // edgeVoice("tr-TR-AhmetNeural", "tr-TR", "male", "Ahmet", "Ahmet", undefined, "Friendly, Positive · General"),
  // edgeVoice("tr-TR-EmelNeural", "tr-TR", "female", "Emel", "Emel", undefined, "Friendly, Positive · General"),
  // edgeVoice("uk-UA-OstapNeural", "uk-UA", "male", "Ostap", "Ostap", undefined, "Friendly, Positive · General"),
  // edgeVoice("uk-UA-PolinaNeural", "uk-UA", "female", "Polina", "Polina", undefined, "Friendly, Positive · General"),
  // edgeVoice("ur-IN-GulNeural", "ur-IN", "female", "Gul", "Gul", undefined, "Friendly, Positive · General"),
  // edgeVoice("ur-IN-SalmanNeural", "ur-IN", "male", "Salman", "Salman", undefined, "Friendly, Positive · General"),
  // edgeVoice("ur-PK-AsadNeural", "ur-PK", "male", "Asad", "Asad", undefined, "Friendly, Positive · General"),
  // edgeVoice("ur-PK-UzmaNeural", "ur-PK", "female", "Uzma", "Uzma", undefined, "Friendly, Positive · General"),
  // edgeVoice("uz-UZ-MadinaNeural", "uz-UZ", "female", "Madina", "Madina", undefined, "Friendly, Positive · General"),
  // edgeVoice("uz-UZ-SardorNeural", "uz-UZ", "male", "Sardor", "Sardor", undefined, "Friendly, Positive · General"),
  // edgeVoice("vi-VN-HoaiMyNeural", "vi-VN", "female", "HoaiMy", "HoaiMy", undefined, "Friendly, Positive · General"),
  // edgeVoice("vi-VN-NamMinhNeural", "vi-VN", "male", "NamMinh", "NamMinh", undefined, "Friendly, Positive · General"),
  edgeVoice("zh-CN-liaoning-XiaobeiNeural", "zh-CN-liaoning", "female", "Xiaobei", "晓北 (Xiaobei)", "晓北", "幽默 · 方言"),
  edgeVoice("zh-CN-shaanxi-XiaoniNeural", "zh-CN-shaanxi", "female", "Xiaoni", "晓妮 (Xiaoni)", "晓妮", "明亮 · 方言"),
  edgeVoice("zh-CN-XiaoxiaoNeural", "zh-CN", "female", "Xiaoxiao", "晓晓 (Xiaoxiao)", "晓晓", "温暖 · 新闻、小说"),
  edgeVoice("zh-CN-XiaoyiNeural", "zh-CN", "female", "Xiaoyi", "晓伊 (Xiaoyi)", "晓伊", "活泼 · 卡通、小说"),
  edgeVoice("zh-CN-YunjianNeural", "zh-CN", "male", "Yunjian", "云健 (Yunjian)", "云健", "激情 · 体育、小说"),
  edgeVoice("zh-CN-YunxiaNeural", "zh-CN", "male", "Yunxia", "云夏 (Yunxia)", "云夏", "可爱 · 卡通、小说"),
  edgeVoice("zh-CN-YunxiNeural", "zh-CN", "male", "Yunxi", "云希 (Yunxi)", "云希", "活泼、阳光 · 小说"),
  edgeVoice("zh-CN-YunyangNeural", "zh-CN", "male", "Yunyang", "云扬 (Yunyang)", "云扬", "专业、可靠 · 新闻"),
  edgeVoice("zh-HK-HiuGaaiNeural", "zh-HK", "female", "HiuGaai", "晓佳 (HiuGaai)", "晓佳", "友善、积极 · 通用"),
  edgeVoice("zh-HK-HiuMaanNeural", "zh-HK", "female", "HiuMaan", "晓曼 (HiuMaan)", "晓曼", "友善、积极 · 通用"),
  edgeVoice("zh-HK-WanLungNeural", "zh-HK", "male", "WanLung", "云龙 (WanLung)", "云龙", "友善、积极 · 通用"),
  edgeVoice("zh-TW-HsiaoChenNeural", "zh-TW", "female", "HsiaoChen", "晓臻 (HsiaoChen)", "晓臻", "友善、积极 · 通用"),
  edgeVoice("zh-TW-HsiaoYuNeural", "zh-TW", "female", "HsiaoYu", "晓雨 (HsiaoYu)", "晓雨", "友善、积极 · 通用"),
  edgeVoice("zh-TW-YunJheNeural", "zh-TW", "male", "YunJhe", "云哲 (YunJhe)", "云哲", "友善、积极 · 通用"),
  // edgeVoice("zu-ZA-ThandoNeural", "zu-ZA", "female", "Thando", "Thando", undefined, "Friendly, Positive · General"),
  // edgeVoice("zu-ZA-ThembaNeural", "zu-ZA", "male", "Themba", "Themba", undefined, "Friendly, Positive · General"),
];

export function findEdgeTtsVoice(id: string): EdgeTtsVoice | undefined {
  const key = id.trim();
  return EDGE_TTS_VOICES.find((v) => v.id === key);
}

export function inferEdgeVoiceGender(id: string): EdgeTtsVoiceGender | undefined {
  return findEdgeTtsVoice(id)?.gender;
}
